# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "master1" do |master1|
        # master1.vm.provider :libvirt do |libvirt|
        #     libvirt.host = "m1.k8s.dev.local"
        # end
        master1.vm.hostname = "m1.k8s.dev.local"
        master1.vm.network :private_network,
            :libvirt__network_name => "master_network",
            :libvirt__netmask => "255.255.255.240",
            :libvirt__forward_mode => "none",
            :libvirt__dhcp_enabled => false,
            :libvirt__host_ip => "10.10.0.1",
            :ip => "10.10.0.2"
    end


    config.vm.define "node1" do |node1|
        # node1.vm.provider :libvirt do |libvirt|
        #     libvirt.host = "n1.k8s.dev.local"
        # end
        node1.vm.hostname = "n1.k8s.dev.local"
    end

    config.vm.define "node2" do |node2|
        # node2.vm.provider :libvirt do |libvirt|
        #     libvirt.host = "n2.k8s.dev.local"
        # end
        node2.vm.hostname = "n2.k8s.dev.local"
    end
end
