# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider :libvirt do |libvirt|
        libvirt.management_network_name = "vagrant-mgmt"
        libvirt.management_network_address = "10.1.1.0/28"
        libvirt.storage_pool_name = "images"  # must be defined if the pool differs from the default
    end

    config.vm.define "master1" do |master1|
        master1.vm.hostname = "m1.k8s.dev.local"
        # static ip for master1
        master1.vm.network :public_network,
            :dev => "mybr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "10.0.0.10"
    end

    config.vm.define "node1" do |node1|
        node1.vm.hostname = "n1.k8s.dev.local"
        # static ip for node1
        node1.vm.network :public_network,
            :dev => "mybr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "10.0.0.20"
    end

    config.vm.define "node2" do |node2|
        node2.vm.hostname = "n2.k8s.dev.local"
        # static ip for node2
        node2.vm.network :public_network,
            :dev => "mybr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "10.0.0.21"
    end
end
