# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Single bionic minimal VM
    config.vm.box = "mai7star/ubuntu"
    config.vm.box_version = "1804.1.0"
    config.vm.synced_folder ".", "/vagrant", disabled: true
end

# NOTE: not working properly yet
