---
# setup cron for removing old bpfmaps and stopping unused execsnoop services

- name: copy cron script
  copy:
    src: cron_remove_old_maps.sh
    dest: "{{ execsnoop_cron_script_abspath }}"
    mode: 0750

- name: ensure the cronjob exists
  cron:
    name: "clean execsnoop bpfmaps"
    job: "{{ execsnoop_cron_script_abspath }} 2>&1 | /usr/bin/logger -t execsnoop_cron_check"
    minute: "{{ execsnoop_cron_time.minute | default(omit) }}"
    hour: "{{ execsnoop_cron_time.hour | default(omit) }}"
