---

- name: setup fswatch
  include_tasks: fswatch.yml

- name: clone sneakpeek to ansible host
  become: false
  delegate_to: "{{ sneakpeek_host }}"
  run_once: true
  git:
    repo: "{{ sneakpeek_repo_url }}"
    version: "{{ sneakpeek_repo_branch }}"
    dest: "{{ sneakpeek_repo_dest }}"

- name: run sneakpeek
  become: false
  delegate_to: "{{ sneakpeek_host }}"
  run_once: true
  command: "{{ sneakpeek_command }}"
  args:
    chdir: "{{ sneakpeek_repo_dest }}"

# the syslog subdir must be writable by syslog
- name: create fswatch syslog base dir
  file:
    path: "{{ fswatch_log_basepath }}"
    state: directory
    group: syslog
    mode: 0775

- name: configure rsyslog for fswatch services
  template:
    src: fswatch_logging.conf.j2
    dest: /etc/rsyslog.d/25-fswatch.conf
  register: rsyslog_config

- name: restart rsyslog
  when: rsyslog_config.changed
  systemd:
    name: rsyslog
    state: restarted

- name: configure systemd services
  include_tasks: services.yml
