---

- hosts: localhost
  roles:
    - role: ansible-kvm
      vars:
        kvm_config: true
        kvm_config_storage_pools: true
        kvm_storage_pools:
          - name: images
            path: /var/lib/libvirt/images/
            autostart: true
            state: active
