---

- hosts: k8s-host
  vars:
    etc_network_interfaces: |
      auto lo
      iface lo inet loopback
  tasks:
    - name: check {{ vagrant_vms_bridge.name }} exists
      failed_when: false
      command: "ip link show {{ vagrant_vms_bridge.name }}"
      register: bridge_presence

    - name: remove bridge
      become: true
      when: bridge_presence.rc == 0
      command: "ip link del {{ vagrant_vms_bridge.name }}"

    - name: reset the etc_network_interfaces
      become: true
      copy:
        content: "{{ etc_network_interfaces }}"
        dest: /etc/network/interfaces

    - name: restart networking
      become: true
      service:
        name: networking
        state: restarted

    - name: halt k8s nodes
      shell: "vagrant halt"
      args:
        chdir: "{{ vagrant_k8s.dir }}"
