---

- hosts: localhost
  vars:
    bridge: mybr0
  pre_tasks:
    - name: install vagrant
      become: true
      package:
        name: vagrant
        state: present
      tags: install
  roles:
    - role: ansible-config-interfaces
      vars:
        config_network_interfaces: true
        network_interfaces:
          - name: "{{ bridge }}"
            configure: true
            enable: true
            method: static
            address: 10.0.0.1
            netmask: 255.255.255.0
            parameters:
              - param: pre-up
                val: "ip link add {{ bridge }} type bridge"
  post_tasks:
    - name: start k8s nodes
      command: "vagrant up"
      args:
        chdir: ../../vagrant_k8s/
