---

- hosts: k8s-host
  vars:
    bridge: mybr0
    etc_network_interfaces: |
      auto lo
      iface lo inet loopback
  tasks:
    - name: check {{ bridge }} exists
      failed_when: false
      command: "ip link show {{ bridge }}"
      register: bridge_presence

    - name: remove bridge
      become: true
      when: bridge_presence.rc == 0
      command: "ip link del {{ bridge }}"

    - name: reset the etc_network_interfaces
      become: true
      copy:
        content: "{{ etc_network_interfaces }}"
        dest: /etc/network/interfaces

    - name: restart networking
      become: true
      service:
        name: networking
        state: restarted

    - name: halt k8s nodes
      command: "vagrant halt"
      args:
        chdir: ../../provisioner/vagrant/
