# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# configuration options: https://www.vagrantup.com/docs/vagrantfile

ENV["LC_ALL"] = "en_US.UTF-8"

BOX_DISTRO = "generic/ubuntu1804"

MASTER_NODE_COUNT = 1
WORKER_NODE_COUNT = 2
DATA_NODE_COUNT = 1
IP_COUNTER = 1

Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|
    config.vm.box = BOX_DISTRO
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider :libvirt do |libvirt|
        libvirt.management_network_name = "vagrant-mgmt"
        libvirt.management_network_address = "10.1.1.0/28"
        libvirt.storage_pool_name = "k8s_images"  # must be defined if the pool differs from the default
    end

    # master nodes
    (1..MASTER_NODE_COUNT).each do |i|
        IP_COUNTER += 1
        config.vm.define "master-#{i}" do |master|
            master.vm.hostname = "m#{i}.k8s.dev.local"
            master.vm.network :public_network,
                :dev => "mybr0",
                :mode => "bridge",
                :type => "bridge",
                :ip => "10.0.0.#{IP_COUNTER}"
            master.vm.post_up_message = "Master node #{i} started"
            master.vm.provision "file", source: "~/.ssh/id_vagrant_k8s.pub", destination: "~/.ssh/id_k8s_host.pub"
            master.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_k8s_host.pub >> /home/vagrant/.ssh/authorized_keys"
        end
    end

    # worker nodes
    (1..WORKER_NODE_COUNT).each do |i|
        IP_COUNTER += 1
        config.vm.define "node-#{i}" do |node|
            node.vm.hostname = "n#{i}.k8s.dev.local"
            node.vm.network :public_network,
                :dev => "mybr0",
                :mode => "bridge",
                :type => "bridge",
                :ip => "10.0.0.#{IP_COUNTER}"
            node.vm.post_up_message = "Worker node #{i} started"
            node.vm.provision "file", source: "~/.ssh/id_vagrant_k8s.pub", destination: "~/.ssh/id_k8s_host.pub"
            node.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_k8s_host.pub >> /home/vagrant/.ssh/authorized_keys"
        end
    end

    # data node simulating remote storage server
    (1..DATA_NODE_COUNT).each do |i|
        IP_COUNTER += 1
        config.vm.define "data-#{i}" do |node|
            node.vm.hostname = "data#{i}.k8s.dev.local"
            node.vm.network :public_network,
                :dev => "mybr0",
                :mode => "bridge",
                :type => "bridge",
                :ip => "10.0.0.#{IP_COUNTER}"
            node.vm.post_up_message = "Data node #{i} started"
            node.vm.provision "file", source: "~/.ssh/id_vagrant_k8s.pub", destination: "~/.ssh/id_k8s_host.pub"
            node.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_k8s_host.pub >> /home/vagrant/.ssh/authorized_keys"
        end
    end
end
