---

all:
  hosts:
    node1:
      ansible_host: m1.k8s-host.local
      ip: 172.30.0.2
      access_ip: 172.30.0.2
    node2:
      ansible_host: n1.k8s-host.local
      ip: 172.30.0.3
      access_ip: 172.30.0.3
    node3:
      ansible_host: n2.k8s-host.local
      ip: 172.30.0.4
      access_ip: 172.30.0.4
  vars:
    ansible_user: vagrant
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
