---
# tasks file for bcc

- name: install dependencies
  apt:
    name: "{{ item }}"
  loop: "{{ bcc_dependencies }}"

- name: clone bcc repository
  git:
    repo: "{{ bcc_repo.url }}"
    version: "{{ bcc_repo.version | default(omit) }}"
    dest: "{{ bcc_repo.dest }}"

- name: create build dir in {{ bcc_repo.dest }}
  file:
    state: directory
    path: "{{ bcc_repo.dest }}/build"

- name: cmake bcc [-DPYTHON_CMD=python]
  shell: >
    cmake -DPYTHON_CMD=python ..
  args:
    chdir: "{{ bcc_repo.dest }}/build"

- name: make bcc
  make:
    chdir: "{{ bcc_repo.dest }}/build"

- name: make install bcc
  make:
    chdir: "{{ bcc_repo.dest }}/build"
    target: install

- name: cmake bcc [-DPYTHON_CMD=python3] - python3 binding
  shell: >
    cmake -DPYTHON_CMD=python3 ..
  args:
    chdir: "{{ bcc_repo.dest }}/build"

- name: make bcc python sources
  make:
    chdir: "{{ bcc_repo.dest }}/build/src/python"

- name: make install bcc python sources
  make:
    chdir: "{{ bcc_repo.dest }}/build/src/python"
    target: install
